SELECT ProductName,Category,Price,
ROW_NUMBER() OVER(PARTITION BY Category ORDER BY Price DESC) RowNum,
RANK() OVER(PARTITION BY Category ORDER BY Price DESC) RankNo,
DENSE_RANK() OVER(PARTITION BY Category ORDER BY Price DESC) DenseRankNo
FROM Products;
